-- 批次信息：主键、批次名称、本次总成本、运费、创建日期、备注
CREATE TABLE PURCHASE (ID TEXT PRIMARY KEY  NOT NULL, BATCH_NAME TEXT, TOTAL_COST NUMERIC, EXPRESS_COST NUMERIC, CREATE_DATE DATE, REMARK TEXT);

-- 进货记录：批次主键、主键、进货日期、种类、数量、进价、货源、总价
CREATE TABLE PURCHASE_DETAIL(ID TEXT PRIMARY KEY NOT NULL,PURCHASE_ID TEXT NOT NULL,PURCHASE_DATE DATE,TYPE TEXT,QUANTITY INT,PURCHASE_PRICE NUMERIC,SOURCE_OF_GOODS TEXT,TOTAL_PRICE NUMERIC);
